FROM ubuntu:22.04
RUN apt-get update && apt-get install -y python3 python3-pip --no-install-recommends && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip3 install -r requirements.txt || exit 1
COPY app.py .
CMD ["python3", "./app.py"]